---
title: "finalgraphs_rmd"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#load required packages
library(tidyr)
library(ggplot2)
library(magrittr)
library(reshape2)
library(lubridate)
library(plyr)
library(dplyr)
library(survival)
library("survminer")
library(viridisLite)
library(directlabels)
library(ggpubr)
library(gridExtra)
library(grid)
library(ggrepel)
```

```{r}
#load required data
survivorship_percents_mario_known <- read.csv('survivorship_percents_mario_known')

survivorship_percents_mario_known$genotype <- c("AZ","BY","CX","DW","EV","FU","GT","HS","IR","JQ")

#load survminer formatted field data
survminer_field <- read.csv("2019_PR_survminer_field.csv")

#reformat all dates to POSIXt format using lubridate and delete old columns
survminer_field$ymd.planted=mdy(survminer_field$date.planted)
survminer_field$ymd.mortality=mdy(survminer_field$date.of.mortality)
#survminer_field <- select(survminer_field, -date.planted, -date.of.mortality)

#calculate number of days between planting and mortality 
survminer_field$days.alive <- difftime(survminer_field$ymd.mortality ,survminer_field$ymd.planted , units = c("days"))

#load total survminer data
survminer_all <- read.csv("2019_PR_survminer_all.csv")

#load survminer formatted cage data
survminer_cage <- read.csv("2019_PR_survminer_cage.csv")

#reformat all dates to POSIXt format using lubridate and delete old columns
survminer_cage$ymd.cage=mdy(survminer_cage$date.put.in.cage)
survminer_cage$ymd.end=mdy(survminer_cage$date.sampled.or.planted)
#survminer_cage <- select(survminer_cage, -date.put.in.cage, -date.sampled.or.planted)

#calculate number of days between put in the cage and being taken out
survminer_cage$days.alive <- difftime(survminer_cage$ymd.end ,survminer_cage$ymd.cage , units = c("days"))

#load growth data
growth_cage <- read.csv("2019_PR_Ofav_growth_CAGE.csv")
growth_field <- read.csv("2019_PR_Ofav_growth_FIELD.csv")

#reformat all dates to POSIXt format using lubridate
growth_cage$ymd.date=mdy(growth_cage$date)
growth_field$ymd.date=mdy(growth_field$date)

#calculate individual growth rates on cage data
growth_cage <- ddply(growth_cage,"coral.ID",transform,
         growth=c(NA,exp(diff(log(area)))-1))

#calculate individual growth rates on field data
growth_field <- ddply(growth_field,"coral.ID",transform,
         growth=c(NA,exp(diff(log(area)))-1))

#combine cage and field data into one dataset
growth_total <- rbind(growth_cage, growth_field)

#create percent growth column by multiplying growth rate by 100 
growth_total$perc.growth <- growth_total$growth*100
#View(growth_total)

#make sure acclimation treatment is being read as a factor 
growth_total$acclimation <- as.factor(growth_total$acclimation)

#load and view data
predation_alt <- read.csv('2019_PR_predation_alt.csv')

#reformat all dates to POSIXt format using lubridate
predation_alt$ymd.mortality=mdy(predation_alt$date.of.mortality)
predation_alt$ymd.planted=mdy(predation_alt$date.sampled.or.planted)

#delete old date columns with dplyr
#predation <- select(predation, -date.of.mortality, -date.sampled.or.planted)

#create new columns with dates between fragmenting and mortality, both known and assumed
predation_alt$daysalive <- difftime(predation_alt$ymd.mortality ,predation_alt$ymd.planted , units = c("days"))

#load growth data
growth_total <- read.csv("2019_PR_Ofav_growth_TOTAL.csv")
```

```{r}
#create survival and survfit objects for all later charts

Surv(survminer_field$days.alive, survminer_field$censored)

surv_object <- Surv(survminer_field$days.alive, survminer_field$censored)

surv_object2 <- Surv(survminer_cage$days.alive, survminer_cage$censored)

surv_object3 <- Surv(survminer_all$days.alive, survminer_all$censored)
```

```{r}
#Kaplan-Meier field data plots separated by acclimation
fit3 <- survfit(surv_object ~ acclimation, data = survminer_field)
fig3 <- ggsurvplot(fit3, data = survminer_field, pval = TRUE, 
                 palette = c("#23BF00","#00C871","#008FD2","#0D00DB","#B900E5"), legend = "bottom", legend.title = "Acclimation Group", legend.labs = c("Group 1: Three Months","Group 2: Two Months","Group 3: One Month","Group 4: Two Weeks","Group 5: No Acclimation")) 
fig3 <- fig3 + guides(colour = guide_legend(ncol = 2))
fig3 <- fig3 + xlab("Days") 
fig3$plot <- fig3$plot + 
              ggplot2::annotate("text", 
                                x = 93, y = 0.44,
                                label = "a", size = 2.5)
fig3$plot <- fig3$plot + 
              ggplot2::annotate("text", 
                                x = 93, y = 0.39,
                                label = "b", size = 2.5)
fig3$plot <- fig3$plot + 
              ggplot2::annotate("text", 
                                x = 93, y = 0.35,
                                label = "a", size = 2.5)
fig3$plot <- fig3$plot + 
              ggplot2::annotate("text", 
                                x = 93, y = 0.26,
                                label = "b", size = 2.5)
fig3$plot <- fig3$plot + 
              ggplot2::annotate("text", 
                                x = 93, y = 0.22,
                                label = "c", size = 2.5)
fig3
```

```{r}
#Kaplan-Meier total data plots separated by fragment location
fit5 <- survfit(surv_object3 ~ location, subset = location %in% c("field","cage"), data = survminer_all)
fig4 <- ggsurvplot(fit5, data = survminer_all, pval = TRUE, legend = "bottom", legend.title = "Fragment Location", legend.labs = c("Cage","Outplanting"), xlim = c(0, 85))
fig4 <- fig4 + xlab("Days")
fig4 <- fig4 + guides(colour = guide_legend(nrow = 2))
fig4
```


```{r}
#Kaplan-Meier field data plots separated by genotype
fit2 <- survfit(surv_object ~ genotype, data = survminer_field)
fig5 <- ggsurvplot(fit2, data = survminer_field, pval = TRUE, legend = "bottom", legend.title = "Genotype", legend.labs = c("AZ","BY","CX","DW","EV","FU","GT","HS","IR","JQ"), xlim = c(0, 100))
fig5 <- fig5 + guides(colour = guide_legend(nrow = 2))
fig5 <- fig5 + xlab("Days")
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.62,
                                label = "bc", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.47,
                                label = "ab", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.43,
                                label = "c", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.39,
                                label = "cd", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.35,
                                label = "c", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.30,
                                label = "c", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.25,
                                label = "ab", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.19,
                                label = "a", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.12,
                                label = "d", size = 2.5)
fig5$plot <- fig5$plot + 
              ggplot2::annotate("text", 
                                x = 94, y = 0.07,
                                label = "abc", size = 2.5)
fig5
```


```{r}
#Kaplan-Meier field data plots separated by bite presence from alt data
surv_object_p <- Surv(predation_alt$daysalive, predation_alt$censored)

fit_p <- survfit(surv_object_p ~ bite.presence, data = predation_alt)
fig6 <- ggsurvplot(fit_p, data = predation_alt, pval = TRUE, legend = "bottom", legend.title = "Bite Presence", legend.labs = c("No predation", "Predation"), xlim = c(0, 85))
fig6 <- fig6 + xlab("Days")
fig6
```


```{r}
#box plot comparing growth rates in cage and in field
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}
fig7 <- ggplot(growth_total, aes(x = location, y = growth)) +
  geom_jitter(aes(color = genotype)) + 
  labs(color = "Genotype")
fig7 <- fig7 + stat_summary(fun.data = MinMeanSEMMax, geom = "boxplot")
fig7 <- fig7 + ylab(bquote('Average Growth per Month '(cm^2)))
fig7 <- fig7 + scale_x_discrete(name = NULL, labels = c("Acclimation Cage","Outplanting"))
fig7 <- fig7 + theme_bw()
fig7 <- fig7 + annotate("label", x = 0.8, y = 2.7, label = "p < 0.001")
fig7
```


```{r}
#box plot comparing growth rates between genotypes
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}
fig8 <- ggplot(growth_total, aes(x = reorder(genotype,growth,na.rm = TRUE), y = growth, color = genotype)) +
  geom_jitter() 
fig8 <- fig8 + stat_summary(fun.data = MinMeanSEMMax, geom = "boxplot")
fig8 <- fig8 + ylab(bquote('Average Growth per Month '(cm^2)))
fig8 <- fig8 + scale_x_discrete(name = "Genotype", labels = c("AZ","IR","JQ","EV","GT","CX","DW","BY","FU","HS"))
fig8 <- fig8 + stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = 1, label.y = 250)
fig8 <- fig8 + theme_bw()
fig8 <- fig8 + theme(legend.position = "none")
fig8 <- fig8 + ylim(-1,3)
fig8
```


```{r}
#box plot comparing growth rates between acclimation times
growth_total$acclimation <- as.factor(growth_total$acclimation)
figS1 <- ggplot(growth_total, aes(x = acclimation, y = growth, color = acclimation)) +
  geom_boxplot() +
  geom_jitter() +
  scale_color_manual(values=c("#23BF00","#00C871","#008FD2","#0D00DB","#B900E5"))
figS1 <- figS1 + scale_x_discrete(name = "Acclimation Group", labels = c("Group 1: Three Months","Group 2: Two Months","Group 3: One Month","Group 4: Two Weeks","Group 5: No Acclimation"))
figS1 <- figS1 + theme_bw()
figS1 <- figS1 + theme(legend.position = "none")
figS1 <- figS1 + ylab(bquote('Average Growth per Month '(cm^2)))
figS1 <- figS1 + stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = 5, label.y = 2.7)
figS1 <- figS1 + ylim(-1,3)
figS1
```
